service: my-express-application

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-2

plugins:
  - serverless-offline

functions:
  app:
    handler: index.handler
    events:
      - http:
           path: /calculate
           method: GET

custom:
  serverless-offline:
    noPrependStageInUrl: true

