import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {Form} from '../components/Calculate'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Student-Loan Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to your Student Loan Calculator
        </h1>

        <Form />

      </main>

      <footer className={styles.footer}>
      
      </footer>
    </div>
  )
}
