import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Student-Loan Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to your Student Loan Calculator
        </h1>

        <label for="currentSalary">Current Salary: 
        <input type="text" placeholder="30000" id="name" name="name" 
             size="20"></input>
           </label>

           <div>
             <button>Submit</button>
           </div>

          

        
        
      </main>

      <footer className={styles.footer}>
      
      </footer>
    </div>
  )
}
